# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document_search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'document_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64ocument_search.proto\x12\x0f\x64ocument_search\x1a\x1cgoogle/protobuf/struct.proto\"<\n\x15\x44ocumentSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0e\n\x01k\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x04\n\x02_k\"B\n\x16\x44ocumentSearchResponse\x12(\n\x07payload\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\x7f\n\x15\x44ocumentSearchService\x12\x66\n\x11RetrieveDocuments\x12&.document_search.DocumentSearchRequest\x1a\'.document_search.DocumentSearchResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENTSEARCHREQUEST']._serialized_start=72
  _globals['_DOCUMENTSEARCHREQUEST']._serialized_end=132
  _globals['_DOCUMENTSEARCHRESPONSE']._serialized_start=134
  _globals['_DOCUMENTSEARCHRESPONSE']._serialized_end=200
  _globals['_DOCUMENTSEARCHSERVICE']._serialized_start=202
  _globals['_DOCUMENTSEARCHSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
