volumes:
  ollama-data:
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  sqlite_server:
    build:
      context: sqlite-server
    container_name: sqlite_server
    ports:
      - "8000:8000"
  document_search:
    build:
      context: document-search
    container_name: document_search
    ports:
      - "50051:50051"
  dw_search:
    build:
      context: dw-search
    container_name: dw_search
    ports:
      - "50052:50051"
    

#   my_app:
#     build:
#       context: my-app
#     container_name: my_app
#     ports:
#       - "2024:2024"
#     depends_on:
#       sqlite_server:
#         condition: service_healthy



  # sub_agent:
  #   build: 
  #     context: sub-agent
  #   container_name: sub_agent
  #   ports:
  #     - "50051:50052"
  #   depends_on:
  #     - ollama
  #   environment:
  #     - OLLAMA_HOST=http://host.docker.internal:11434
